services:
  - type: web
    name: admin-panel-geo-attend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    preDeployCommand: php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_TIMEZONE
        value: Asia/Jakarta
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
